name: Build APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Получаем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Устанавливаем JDK
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      # 3. Даем права gradlew
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 4. Сборка APK
      - name: Build APK
        run: ./gradlew assembleDebug

      # 5. Сохранение артефакта (.apk)
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk